name: Setup Repo
description: Setup pnpm and Node.js, install dependencies

inputs:
  node-version:
    description: Version of Node to use
    default: 24.x

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
