name: Setup Repo
description: Setup pnpm and Node.js, install dependencies

inputs:
  node-version:
    description: Version of Node to use
    default: 24.x

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@91ab88e2619ed1f46221f0ba42d1492c02baf788 # v6
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
